### ISSUE TITLE
Can we train on other dataset than Coco?

### ISSUE THREAD

**Issue by aspenlin** [scnuhealthy/Tensorflow_PersonLab#3]
Thanks!

**Comment by aspenlin** [comment]
Can you also add more specific information about each file and how to run them etc.. Like how to generate the images in demo_result?

**Comment by aspenlin** [comment]
I was able to generate the images in demo_result by simply running demo.py as you stated in README. What I meant is putting more annotations to each .py file so people can better understand your code though. Thanks!

**Comment by scnuhealthy** [comment]
Firstyly, most of the files will be used in training, and each file's function is as their names straightforwardly. Sorry for my busyness and not to put more code mements. If you are focus on how to generate the images, you need to read the paper to understand the whole decode process, because this part of code is quite complex. 
Next, if you want to train other datasets, the most simplest way is to change their annotations to coco format. Their are many guide on Internet to help you.
